### ISSUE TITLE
AWS keys exposed in appveyor.yml - you should remove and reset your keys

### ISSUE THREAD

**Issue by sawilde** [naturalatlas/node-gdal#81]
https://github.com/naturalatlas/node-gdal/blob/master/appveyor.yml

````
environment:
  AWS_ACCESS_KEY_ID:
    secure: ihP9C8AMdicFGeffdKqgNG1O4n68jDHQPAZCB/IfuZg=
  AWS_SECRET_ACCESS_KEY:
    secure: G45Qz4paCV4VpsA939dz7i2PQiTdVOYwh1paZ3sGSdS9REKnLHB2cmToak8uAyHP
  matrix:
    - nodejs_version: "0.10.32"
    - nodejs_version: "0.11.13"
````
